export const effectTypes = [
  "happy",
  "euphoric",
  "uplifted",
  "sleepy",
  "dry_mouth",
  "dry_eyes",
  "dizzy",
  "paranoid",
  "anxious",
  "stress",
  "depression",
  "pain",
  "anxiety",
  "insomnia",
  "hungry",
  "talkative",
  "ptsd",
  "creative",
  "energetic",
  "fatigue",
  "focused",
  "lack_of_appetite",
  "headache",
  "giggly",
  "nausea",
  "inflammation",
  "relaxed",
];

export const terpenes = [
  "caryophyllene",
  "limonene",
  "myrcene",
  "terpinolene",
  "pinene",
];

export const types = ["Hybrid", "Sativa", "Indica"];

export const effectCriteria = {
  good: [
    "happy",
    "euphoric",
    "uplifted",
    "stress",
    "depression",
    "pain",
    "anxiety",
    "insomnia",
    "hungry",
    "talkative",
    "ptsd",
    "creative",
    "energetic",
    "focused",
    "giggly",
    "nausea",
    "inflammation",
    "relaxed",
  ],
  neutral: ["sleepy", "fatigue", "lack_of_appetite", "headache"],
  bad: ["dry_mouth", "dry_eyes", "dizzy", "paranoid", "anxious"],
};
